WD: 0.005
WT: MSVFVSGANGFIAQHIVDLLLKEDYKVIGSARSQEKAENLTEAFGNNPKFSMEVVPDISKLDAFDHVFQKHGKDIKIVLHTASPFCFDITDSERDLLIPAVNGVKGILHSIKKYAADSVERVVLTSSYAAVFDMAKENDKSLTFNEESWNPATWESCQSDPVNAYCGSKKFAEKAAWEFLEENRDSVKFELTAVNPVYVFGPQMFDKDVKKHLNTSCELVNSLMHLSPEDKIPELFGGYIDVRDVAKAHLVAFQKRETIGQRLIVSEARFTMQDVLDILNEDFPVLKGNIPVGKPGSGATHNTLGATLDNKKSKKLLGFKFRNLKETIDDTASQILKFEGRI
batch_size: 16
data_filepath: normalized_processed_BI_R1_dataset_w_quantiles.pkl
decay: 0.8
embedding_type: all_tokens
epoch_threshold_to_unlock_ESM2: 100
epochs: 2000
grad_clip_threshold: 3.0
huggingface_identifier: esm2_t33_650M_UR50D
learning_rate: 1.0e-06
lr_mult: 1
lr_mult_factor: 1
max_num_layers_unfreeze_each_epoch: 36
num_layers_unfreeze_each_epoch: 15
num_reg_tasks: 1
num_unfrozen_layers: 27
reg_weights: 1
reinit_optimizer: 0
seed: 3
slen: 342
use_scheduler: 1
using_EMA: 1
warm_restart: 1
